# Generated by Django 3.1 on 2022-02-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20220206_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzeria',
            name='email',
            field=models.EmailField(max_length=245),
        ),
        migrations.AlterField(
            model_name='pizzeria',
            name='phone_number',
            field=models.PositiveIntegerField(max_length=11),
        ),
    ]
