# Generated by Django 3.1 on 2022-02-06 05:21

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20220206_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzeria',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=11, region=None),
        ),
    ]
